"""Gate 3: measured native differences, exact SHINE working/terminal values."""
from functools import lru_cache
import hashlib
import json
from pathlib import Path

import numpy as np
import pytest
from scipy.io import loadmat
from shine_color import color
from shine_color.numeric import to_uint8

FIXTURES = Path(__file__).with_name('fixtures')/'color_adapter'
GROUPS = ('palette','structured','gray_ramp','dark','random','boundaries')
# Fixed observed maxima from measurements.json. Never regenerated by pytest.
# rtol=0 throughout; these are corpus/environment-specific float bounds.
FORWARD = {'lab':[1.4210854715202004e-14,1.1368683772161603e-13,5.684341886080802e-14],
           'hsv':[8.881784197001252e-16,2.498001805406602e-16,1.1102230246251565e-16]}
# Native inverse bounds below are set after the isolated-inverse measurements.
INVERSE = {
    ('lab','native'):[7.167877402736167e-15,2.796374243274613e-15,7.389922007661198e-16],
    ('lab','work'):[7.17134684968812e-15,1.8318679906315083e-15,9.159339953157541e-16],
    ('lab','processed'):[7.17134684968812e-15,1.7937040741600185e-15,9.159339953157541e-16],
    ('hsv','native'):[6.938893903907228e-16,2.220446049250313e-16,9.43689570931383e-16],
    ('hsv','work'):[6.938893903907228e-16,2.220446049250313e-16,9.43689570931383e-16],
    ('hsv','processed'):[6.938893903907228e-16,2.220446049250313e-16,9.43689570931383e-16],
}
RECONSTRUCTION = {
    ('lab','work'):[1.111610803405938e-14,4.565792188770956e-15,1.915134717478395e-15],
    ('lab','processed'):[1.111610803405938e-14,4.565792188770956e-15,1.915134717478395e-15],
    ('hsv','work'):[8.881784197001252e-16,9.159339953157541e-16,1.2490009027033011e-15],
    ('hsv','processed'):[8.881784197001252e-16,9.159339953157541e-16,1.2490009027033011e-15],
}
ROUNDTRIP = {
    'lab':[1.0217521273503394e-14,5.169475958410885e-15,1.5543122344752192e-15],
    'hsv':[7.771561172376096e-16,9.43689570931383e-16,1.2490009027033011e-15],
}


@lru_cache(maxsize=8)
def fixture(name):
    manifest=json.loads((FIXTURES/'measurements.json').read_text())
    path=FIXTURES/(name+'.mat')
    assert hashlib.sha256(path.read_bytes()).hexdigest()==manifest['fixture_sha256'][path.name]
    return loadmat(path)


def native_equal(actual, expected, bound):
    assert actual.dtype == expected.dtype == np.float64
    assert actual.shape == expected.shape
    for channel, maximum in enumerate(bound):
        np.testing.assert_allclose(actual[...,channel], expected[...,channel], atol=maximum, rtol=0)


@pytest.mark.parametrize('name',GROUPS)
@pytest.mark.parametrize('space',['lab','hsv'])
def test_forward_native(name,space):
    f=fixture(name)
    convert=color.rgb_to_lab_octave if space=='lab' else color.rgb_to_hsv
    actual=convert(f['rgb'])
    native_equal(actual,f[space],FORWARD[space])


@pytest.mark.parametrize('name',GROUPS)
@pytest.mark.parametrize('space',['lab','hsv'])
def test_exact_working_scales(name,space):
    f=fixture(name)
    if space=='lab':
        native=color.rgb_to_lab_octave(f['rgb'])
        actual=color.l_to_working(native[...,0])
        expected=f['l_work']
        inverse=color.working_to_l(actual)
        reference=f['lab_work'][...,0]
    else:
        native=color.rgb_to_hsv(f['rgb'])
        actual=color.v_to_working(native[...,2])
        expected=f['v_work']
        inverse=color.working_to_v(actual)
        reference=f['hsv_work'][...,2]
    assert actual.dtype == np.uint8
    np.testing.assert_array_equal(actual,expected)
    np.testing.assert_array_equal(inverse,reference)


@pytest.mark.parametrize('name',GROUPS)
@pytest.mark.parametrize('space',['lab','hsv'])
def test_end_to_end_native_roundtrip(name,space):
    f=fixture(name)
    forward=color.rgb_to_lab_octave if space=='lab' else color.rgb_to_hsv
    inverse=color.lab_to_rgb_octave if space=='lab' else color.hsv_to_rgb
    actual=inverse(forward(f['rgb']))
    native_equal(actual,f[space+'_roundtrip'],ROUNDTRIP[space])
    np.testing.assert_array_equal(to_uint8(actual*255),f[space+'_roundtrip_u8'])
    np.testing.assert_array_equal(to_uint8(actual*255),f['rgb'])


@pytest.mark.parametrize('name',GROUPS)
@pytest.mark.parametrize('space',['lab','hsv'])
@pytest.mark.parametrize('variant',['native','work','processed'])
def test_isolated_inverse(name,space,variant):
    f=fixture(name)
    convert=color.lab_to_rgb_octave if space=='lab' else color.hsv_to_rgb
    source=space if variant=='native' else space+'_'+variant
    expected=space+'_roundtrip' if variant=='native' else space+'_'+variant+'_rgb'
    terminal=space+'_roundtrip_u8' if variant=='native' else space+'_'+variant+'_u8'
    actual=convert(f[source])
    native_equal(actual,f[expected],INVERSE[(space,variant)])
    np.testing.assert_array_equal(to_uint8(actual*255),f[terminal])


@pytest.mark.parametrize('name',GROUPS)
@pytest.mark.parametrize('space',['lab','hsv'])
@pytest.mark.parametrize('variant',['work','processed'])
def test_public_working_reconstruction(name,space,variant):
    f=fixture(name)
    parts=getattr(color,'split_'+space)(f['rgb'])
    original=[p.copy() for p in parts]
    native=getattr(color,'rgb_to_lab_octave' if space=='lab' else 'rgb_to_hsv')(f['rgb'])
    indices=(1,2) if space=='lab' else (0,1)
    for index in indices:
        np.testing.assert_array_equal(parts[index],native[...,index])
    processed=list(parts)
    if variant=='processed':
        index=0 if space=='lab' else 2
        processed[index]=np.maximum(processed[index],128)
    actual=getattr(color,'merge_'+space)(*processed)
    native_equal(actual,f[space+'_'+variant+'_rgb'],RECONSTRUCTION[(space,variant)])
    np.testing.assert_array_equal(to_uint8(actual*255),f[space+'_'+variant+'_u8'])
    for a,b in zip(parts,original):
        np.testing.assert_array_equal(a,b)


@pytest.mark.parametrize('name',GROUPS)
def test_rgb_working_channels(name):
    original=fixture(name)['rgb']
    parts=color.split_rgb(original)
    np.testing.assert_array_equal(color.merge_rgb(*parts),original)
    for k,part in enumerate(parts):
        assert part.dtype==np.uint8 and not np.shares_memory(part,original)
        np.testing.assert_array_equal(part,original[...,k])


def test_lab_gamut_is_unclipped():
    f=fixture('inverse')
    actual=color.lab_to_rgb_octave(f['lab'])
    native_equal(actual,f['rgb'],[5.329070518200751e-15,1.4344081298162521e-15,4.440892098500626e-16])
    assert np.count_nonzero(actual<0)==422
    assert np.count_nonzero(actual>1)==242
    np.testing.assert_array_equal(actual<0,f['rgb']<0)
    np.testing.assert_array_equal(actual>1,f['rgb']>1)
    np.testing.assert_array_equal(to_uint8(actual*255),f['rgb_u8'])


@pytest.mark.parametrize('space',['hsv','lab'])
def test_recombination_preserves_chroma_exactly(space,monkeypatch):
    # Inspect the actual native array passed to the inverse, not just rounded RGB.
    chroma1=np.array([[0.123456789012345,-0.246813579]])
    chroma2=np.array([[0.864197532,83.357913579]])
    working=np.array([[0,255]],dtype=np.uint8)
    if space=='lab':
        monkeypatch.setattr(color,'lab_to_rgb_octave',lambda a:a)
        actual=color.merge_lab(working,chroma1,chroma2)
        np.testing.assert_array_equal(actual[...,1],chroma1)
        np.testing.assert_array_equal(actual[...,2],chroma2)
    else:
        monkeypatch.setattr(color,'hsv_to_rgb',lambda a:a)
        actual=color.merge_hsv(chroma1,chroma2,working)
        np.testing.assert_array_equal(actual[...,0],chroma1)
        np.testing.assert_array_equal(actual[...,1],chroma2)


def test_known_dark_cast_boundary():
    rgb=np.array([[[0,1,0]]],dtype=np.uint8)
    native=color.rgb_to_lab_octave(rgb)
    assert native[0,0,0]*2.55 > .5
    np.testing.assert_array_equal(color.l_to_working(native[...,0]),[[1]])


@pytest.mark.parametrize('convert',[color.rgb_to_lab_octave,color.rgb_to_hsv,color.split_rgb])
def test_rgb_requires_explicit_uint8(convert):
    with pytest.raises(TypeError,match='uint8'):
        convert(np.array([[0.,.5,1.]]))
    with pytest.raises(ValueError,match='three'):
        convert(np.zeros((2,4),dtype=np.uint8))


@pytest.mark.parametrize('convert',[color.working_to_l,color.working_to_v])
def test_working_requires_explicit_uint8(convert):
    with pytest.raises(TypeError,match='uint8'):
        convert(np.array([128.]))


def test_reference_derived_boundary_selection():
    selection=json.loads((FIXTURES/'boundary_selection.json').read_text())
    candidates=json.loads((FIXTURES/'candidates.json').read_text())
    spec=Path(__file__).resolve().parents[2]/'docs/OCTAVE_LAB_SPEC.md'
    assert hashlib.sha256(spec.read_bytes()).hexdigest()==candidates['specification_sha256']
    pool=fixture('candidates')['search']
    selected=fixture('boundaries')
    indices=np.array(selection['pool_indices_one_based'])-1
    np.testing.assert_array_equal(selected['rgb'][:,0,:],pool[indices])
    scaled=selected['lab'][:,0,0]*2.55
    offset=scaled-(np.array(selection['k'])+.5)
    assert len(indices)==337 and not selection['exact_tie_pool_indices']
    assert np.all(np.abs(offset)<=.001)
    np.testing.assert_array_equal(np.sign(offset),selection['side'])
    np.testing.assert_array_equal(scaled,np.array(selection['selected_scaled_l']).ravel())


def test_dark_cube_and_random_inputs_not_filtered():
    dark=fixture('dark')['rgb'][:,0,:]
    np.testing.assert_array_equal(dark,np.indices((33,33,33)).reshape(3,-1).T)
    generator=np.random.Generator(np.random.PCG64(2026091401))
    np.testing.assert_array_equal(fixture('random')['rgb'][:,0,:],
                                  generator.integers(0,256,(65536,3),dtype=np.uint8))
